### ISSUE TITLE
Abandoned Project?

### ISSUE THREAD

**Issue by tonytonyistony** [flakas/reconbot#11]
Has this project been abandoned?

**Comment by flakas** [comment]
@tonytonyistony thanks for the question.
The project is in maintenance mode. I'll fix more significant issues, update ESI endpoints when they change, but I don't have any plans for new features.

Is there anything specific you are looking for?

**Comment by tonytonyistony** [comment]
I just hadn't seen any activity in the issue board in quite a while, I wanted to see how long it would take to get a response.

I actually just finished setting up your reconbot and Im having a hell of time getting it to post things in my discord. Whats even more frustrating is Im getting no errors in the logs or anything. So Im not quite sure what is breaking.

Do you have a slack or discord I could join to ask some questions about this? Or should I stick to this issue board for support?

**Comment by flakas** [comment]
Sorry to hear the tool is causing silent issues.
There is no message board for the project, but you can reach me at `The Random One#5205` on Discord.

**Comment by tonytonyistony** [comment]
Ill hit you up tomorrow. Its getting late here and didn't think you would message back so fast. I've been messing with this most of the day and I need to get some sleep.

**Comment by tonytonyistony** [comment]
@flakas I sent you a friend request in discord

**Comment by flakas** [comment]
I'll close this ticket as we kind of figured it out.
Only a subset of notifications was whitelisted, so triggered ones during testing didn't show up.

As a future improvement, I'll configure the default `run.py` to allow all supported notification types.

Thanks for your help!
