### ISSUE TITLE
Whitelisting of notifications doesnt have any effect

### ISSUE THREAD

**Issue by heresboris** [flakas/reconbot#12]
es per run.py i did whitelist the notification that i need but it still spits out everything that comes in to discord webhook. it is as if whitelist has no effect.

**Comment by flakas** [comment]
Hey @heresboris,

Thanks for the issue report.
I was able to reproduce the issue and it should be fixed by be423cc commit.

Could you please pull from `master` and let me know if that fixes the issue?

Thanks!

**Comment by flakas** [comment]
I'll close this issue as fixed for the time being, but if you experience any further issues - please let me know. Thanks!
