### ISSUE TITLE
ESI Callback URL

### ISSUE THREAD

**Issue by tonytonyistony** [flakas/reconbot#13]
Your installation documentation is 90% complete... You are missing what callback URL you are supposed to specify during ESI application creation.

Could you provide this information please?

**Comment by flakas** [comment]
Hello @tonytonyistony,

Thanks pointing out the missing link, you're right!
Reconbot does not provide an endpoint itself, but you can follow the first 2 parts of [Fuzzysteve's "Using ESI on Google Sheets" guide](https://www.fuzzwork.co.uk/2017/03/14/using-esi-google-sheets/) to get `refresh_token` of your accounts.

In the guide Fuzzysteve uses `Postman` tool to authorize his account on ESI, so he used `https://www.getpostman.com/oauth2/callback` for the `ESI Callback URL`.

Let me know if that helps.

**Comment by tonytonyistony** [comment]
Oh yeah I knew about it. I was just letting you know its not in your documentation on your WIKI. The only way to discover that is in your config file in a comment. You should put it in the WIKI and call it a day.

**Comment by flakas** [comment]
Got it. I've added a snippet to `README` about it.
Good suggestion, thank you!
