### ISSUE TITLE
bad request 400 client error

### ISSUE THREAD

**Issue by ysm1mh** [flakas/reconbot#3]
so i did everything according to the instructions.

i get this error.

Traceback (most recent call last):
  File "/reconbot/reconbot/tasks.py", line 15, in esi_notification_task
    notifications = esi.get_new_notifications(max_age=MAX_NOTIFICATION_AGE_IN_SECONDS)
  File "/reconbot/reconbot/esi.py", line 32, in get_new_notifications
    notifications = self.get_notifications()
  File "/reconbot/reconbot/esi.py", line 29, in get_notifications
    return self.esi_get(url)
  File "/reconbot/reconbot/esi.py", line 87, in esi_get
    query['token'] = self.sso.get_access_token()
  File "/reconbot/reconbot/sso.py", line 18, in get_access_token
    return self.fetch_access_token()
  File "/reconbot/reconbot/sso.py", line 37, in fetch_access_token
    r.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://login.eveonline.com/oauth/token
400 Client Error: Bad Request for url: https://login.eveonline.com/oauth/token

what does it mean?

**Comment by flakas** [comment]
You need to specify character ID and `refresh_token` in [run.py](https://github.com/flakas/reconbot/blob/e24693fc62d829d03a8e909a5598e10bf939286b/run.py#L48).
I realize README.md glances over that part.

You can follow the FuzzySteve's guide [Using ESI with Google Sheets](https://www.fuzzwork.co.uk/2017/03/14/using-esi-google-sheets/) to get the `refresh_token` of your characters.

**Comment by ysm1mh** [comment]
i did the caracter ID and refresh token according to https://www.fuzzwork.co.uk/2017/03/14/using-esi-google-sheets/

possible that my caracter id might not be correct.

how do i get my ID then?

**Comment by flakas** [comment]
You can look up the character ID e.g. by looking it up in zkillboard.
E.g. for CCP Falcon the URL is: https://zkillboard.com/character/92532650/
So character ID will be `92532650`.

I'm closing this issue since you seem to be past this point.
