### ISSUE TITLE
bad request when sending message to discord

### ISSUE THREAD

**Issue by ysm1mh** [flakas/reconbot#5]
it seems that xinc got his issue fixed changing from python 3.5 to 3.6. #4 

i am using python 3.6 and my issue isnt fixed.  not working.

[2018-05-07 03:16:29.153391] Exception in esi_notification_task
------------------------------------------------------------
Traceback (most recent call last):
  File "/reconbot/reconbot/tasks.py", line 28, in esi_notification_task
    notifier.notify(message)
  File "/reconbot/reconbot/notifiers/caching.py", line 14, in notify
    self.notifier.notify(text, options)
  File "/reconbot/reconbot/notifiers/splitter.py", line 7, in notify
    notifier.notify(text, options)
  File "/reconbot/reconbot/notifiers/discord.py", line 17, in notify
    loop.run_until_complete(self._send_message(channel_id, text))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/reconbot/reconbot/notifiers/discord.py", line 24, in _send_message
    await self.client.send_message(c, message)
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "/usr/lib/python3.6/site-packages/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400): Unauthorized
BAD REQUEST (status code: 400): Unauthorized

**Comment by Husteln** [comment]
Your bot has to come online at least once in order for all of this to work. I have been banging my head on this up until now, when I ran a simple test script where bot did come online.

:S

**Comment by flakas** [comment]
@Husteln the current way of operation is that the bot will connect to discord only to post new messages and then it will disconnect from discord. Which may be why you are not seeing it coming online.

Aside from that, if you have any questions or issues please do create a separate GitHub issue for that, as your question does not seem to be related to the Exception mentioned in the parent of this issue.

**Comment by Husteln** [comment]
@flakas I had exact same problem, which was fixed by the actions I described.

**Comment by flakas** [comment]
Oh, I misunderstood your comment. My bad, sorry.

Could you please share the sample script that helped in your case?
Perhaps it could help others experiencing the same issue as well.

**Comment by Husteln** [comment]
It is the quick example script from the discord.py page. That one is obviously incomplete, but I only needed it to fire the bot up, so I put in my token and ran it.

**Comment by GhostMB** [comment]
is there a solution

**Comment by flakas** [comment]
@GhostMB See if the [discord.py](https://github.com/Rapptz/discord.py) example works for you first, as suggested by Husteln.
If not, personally I'm having trouble reproducing this issue on my end and am no closer to resolving it or suggesting a solution, unfortunately.

**Comment by flakas** [comment]
If you or anyone else are still experiencing the "Bad Request" issue when posting notifications to Discord, please consider trying the Discord Webhook approach outlined in `README.md`.
It has just been added via #10.

**Comment by flakas** [comment]
I'll close this issue, but as mentioned before, if you are experiencing issues with the Discord Bot notifier, try using the Discord Webhook notifier.
